language: go
os: linux
dist: focal
services:
  - docker
branches:
  only:
  - main

before_install:
  - nvm install lts/*
  - npm install
  - npx semantic-release

after_success:
  - echo $GCP_AR_KEY | docker login -u _json_key --password-stdin us-east1-docker.pkg.dev
  - npm run docker-deploy
