language: golang

services:
  - docker

before_install:
  - echo $GCP_AR_KEY | docker login -u _json_key --password-stdin us-east1-docker.pkg.dev
  - docker build -t us-east1-docker.pkg.dev/bernot-dev/garmin-test/latest .
  - docker push us-east1-docker.pkg.dev/bernot-dev/garmin-test/latest