language: go
os: linux
dist: focal
services:
  - docker

jobs:
  include:
    - stage: Test and Release
      name: Go Test
      script:
        - go test -v ./...
        - nvm install lts/*
        - npx semantic-release
    - stage: Docker Build and Push
      script:
        - echo $GCP_AR_KEY | docker login -u _json_key --password-stdin us-east1-docker.pkg.dev
        - docker build -t us-east1-docker.pkg.dev/bernot-dev/garmin-test/garmin-test .
        - docker push us-east1-docker.pkg.dev/bernot-dev/garmin-test/garmin-test