language: go
os: linux
dist: focal
services:
  - docker

jobs:
  include:
    - stage: test
      script: go test -v ./...
    - stage: build
      script: docker build -t us-east1-docker.pkg.dev/bernot-dev/garmin-test/garmin-test .
    - stage: deploy
      before_script: echo $GCP_AR_KEY | docker login -u _json_key --password-stdin us-east1-docker.pkg.dev
      script: docker push us-east1-docker.pkg.dev/bernot-dev/garmin-test/garmin-test
